const italy = [
  "/photos/italy/italy1.JPG",
  "/photos/italy/italy2.JPG",
  "/photos/italy/italy3.JPG",
  "/photos/italy/italy4.JPG",
  "/photos/italy/italy5.JPG",
  "/photos/italy/italy6.JPG",
  "/photos/italy/italy7.JPG",
  "/photos/italy/italy9.JPG",
  "/photos/italy/italy10.JPG",
  "/photos/italy/italy11.JPG",
  "/photos/italy/italy12.JPG",
  "/photos/italy/italy13.JPG",
  "/photos/italy/italy14.JPG",
  "/photos/italy/italy15.JPG",
  "/photos/italy/italy16.JPG",
  "/photos/italy/italy17.JPG",
  "/photos/italy/italy18.JPG",
  "/photos/italy/italy19.JPG",
  "/photos/italy/italy20.JPG",
  "/photos/italy/italy21.JPG",
  "/photos/italy/italy22.JPG",
  "/photos/italy/italy23.JPG",
  "/photos/italy/italy24.JPG",
  "/photos/italy/italy25.JPG",
];

const new_mexico = [
  "/photos/new-mexico/nm1.JPG",
  "/photos/new-mexico/nm2.JPG",
  "/photos/new-mexico/nm3.JPG",
  "/photos/new-mexico/nm4.JPG",
  "/photos/new-mexico/nm5.JPG",
  "/photos/new-mexico/nm6.JPG",
  "/photos/new-mexico/nm7.JPG",
  "/photos/new-mexico/nm8.JPG",
  "/photos/new-mexico/nm9.JPG",
  "/photos/new-mexico/nm10.JPG",
  "/photos/new-mexico/nm11.JPG",
  "/photos/new-mexico/nm12.JPG",
  "/photos/new-mexico/nm13.JPG",
  "/photos/new-mexico/nm14.JPG",
  "/photos/new-mexico/nm15.JPG",
  "/photos/new-mexico/nm16.JPG",
  "/photos/new-mexico/nm17.JPG",
  "/photos/new-mexico/nm18.JPG",
  "/photos/new-mexico/nm19.JPG",
  "/photos/new-mexico/nm20.JPG",
  "/photos/new-mexico/nm21.JPG",
  "/photos/new-mexico/nm22.JPG",
  "/photos/new-mexico/nm23.JPG",
  "/photos/new-mexico/nm24.JPG",
  "/photos/new-mexico/nm25.JPG",
  "/photos/new-mexico/nm26.JPG",
  "/photos/new-mexico/nm27.JPG",
  "/photos/new-mexico/nm28.JPG",
];

const lon_edi = [
  "/photos/lon-edi/castle.jpg",
  "/photos/lon-edi/edi-street.jpg",
  "/photos/lon-edi/lights.jpg",
  "/photos/lon-edi/museum.jpg",
  "/photos/lon-edi/lon-street.jpg",
];

const sf = [
  "/photos/sf/sf1.jpg",
  "/photos/sf/sf2.jpg",
  "/photos/sf/sf3.jpg",
  "/photos/sf/sf4.jpg",
  "/photos/sf/sf5.jpg",
  "/photos/sf/sf6.jpg",
];

const la = [
  "/photos/la/la1.JPG",
  "/photos/la/la2.JPG",
  "/photos/la/la3.JPG",
  "/photos/la/la4.JPG",
  "/photos/la/la5.JPG",
  "/photos/la/la6.JPG",
  "/photos/la/la7.JPG",
];

const vegas = [
  "/photos/vegas/vegas1.jpg",
  "/photos/vegas/vegas2.jpg",
  "/photos/vegas/vegas3.jpg",
  "/photos/vegas/vegas4.jpg",
  "/photos/vegas/vegas5.jpg",
  "/photos/vegas/vegas6.jpg",
  "/photos/vegas/vegas7.jpg",
  "/photos/vegas/vegas8.jpg",
  "/photos/vegas/vegas9.jpg",
  "/photos/vegas/vegas10.jpg",
  "/photos/vegas/vegas11.jpg",
  "/photos/vegas/vegas12.jpg",
  "/photos/vegas/vegas13.jpg",
  "/photos/vegas/vegas14.jpg",
  "/photos/vegas/vegas15.jpg",
];

const japan = [
  "/photos/japan/jp1.jpeg",
  "/photos/japan/jp2.jpeg",
  "/photos/japan/jp3.jpeg",
  "/photos/japan/jp4.jpeg",
  "/photos/japan/jp5.jpeg",
  "/photos/japan/jp6.jpeg",
  "/photos/japan/jp7.jpeg",
  "/photos/japan/jp8.jpeg",
  "/photos/japan/jp9.jpeg",
  "/photos/japan/jp10.jpeg",
  "/photos/japan/jp11.jpeg",
  "/photos/japan/jp12.jpeg",
  "/photos/japan/jp13.jpeg",
  "/photos/japan/jp14.jpeg",
  "/photos/japan/jp15.jpeg",
  "/photos/japan/jp16.jpeg",
  "/photos/japan/jp17.jpeg",
  "/photos/japan/jp18.jpeg",
  "/photos/japan/jp19.jpeg",
];

export const photos = {
  italy,
  new_mexico,
  lon_edi,
  sf,
  la,
  vegas,
  japan,
};
